### Prueba de conexión
GET http://localhost:3000/

### Registro de usuario
POST http://localhost:3000/registro
Content-Type: application/json

{
    "nombre_usuario": "Guillermo",
    "apellido_usuario": "Gonzalez",
    "fecha_nacimiento_usuario": "2005-09-09",
    "fk_genero": 2,
    "email_usuario": "memorex@gmail.com",
    "telefono_usuario": 6144514145,
    "contrasena_usuario": "memorex"
}

### Inicio de sesión
POST http://localhost:3000/login
Content-Type: application/json

{
    "email_usuario": "memorex@gmail.com",
    "contrasena_usuario": "memorex"
}
